# Generated by Django 3.0.7 on 2020-07-05 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificates',
            name='body',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='certificates',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='certificates',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
