# Generated by Django 3.0.7 on 2020-07-06 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='imges/')),
                ('title', models.CharField(max_length=255, null=True)),
                ('body', models.TextField(null=True)),
            ],
        ),
    ]
