# Generated by Django 3.0.7 on 2020-07-06 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tech',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='type',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
